// import './globals.css';

// import Provider from './components/Provider'
// import { Analytics } from '@vercel/analytics/react';
// import Nav from './nav';
// import Toast from './toast';
// import { Suspense } from 'react';

// export const metadata = {
//   title: 'Next.js 13 + PlanetScale + NextAuth + Tailwind CSS',
//   description:
//     'A user admin dashboard configured with Next.js, PlanetScale, NextAuth, Tailwind CSS, TypeScript, ESLint, and Prettier. And now is mine!'
// };

// export default async function RootLayout({
//   children
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en" className="h-full bg-gray-50">
//       <body className="h-full">
//         <Provider>
//           <Suspense fallback="...">
//             {/* @ts-expect-error Server Component */}
//             <Nav />
//           </Suspense>
//           {children}
//           <Analytics />
//           {/* <Toast /> */}
//         </Provider>
//       </body>
//     </html>
//   );
// }
import Provider from './components/Provider'
import Header from './components/Header'
import Footer from './components/Footer'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang='en'
      className={`${inter.className} h-full scroll-smooth antialiased`}
    >
      <body className='flex h-full flex-col'>
        <Provider>
          <Header />
          <main className='grow'>{children}</main>
          <Footer />
        </Provider>
      </body>
    </html>
  )
}
